/**
 * LIGHT THEME VARIANTS
 * Each light theme mirrors its dark counterpart's accent/semantic colors
 * while inverting backgrounds and foregrounds for light mode.
 */

import type { GlobalTheme } from './themeTypes'

const lightDefaults = {
  typography: {
    fontFamily: 'IBM Plex Mono, monospace',
    letterSpacing: '0.03em',
    textTransform: 'none' as const,
  },
  effects: {
    borderRadius: '0' as const,
    transitionDuration: 'none' as const,
    scanlines: false,
    textShadow: false,
  },
  components: {
    button: { borderWidth: '2px', shadowOffset: '4px' },
    input: { borderWidth: '2px', focusRingWidth: '2px' },
    card: { borderWidth: '2px', shadowIntensity: 0.3 },
    modal: { backdropOpacity: 0.5, borderWidth: '2px' },
  },
}

// ─── OBSIDIAN LIGHT ─────────────────────────────────
export const obsidianLightTheme: GlobalTheme = {
  name: "OBSIDIAN LIGHT",
  description: "LTF1 signature — Indigo accent on clean white",
  colors: {
    background: '#FAFAFA',
    backgroundSecondary: '#F0F0F5',
    backgroundTertiary: '#E8E8F0',
    foreground: '#1A1A2E',
    foregroundSecondary: '#4A4A60',
    foregroundTertiary: '#8888A0',
    border: '#D0D0E0',
    borderHover: '#B0B0C8',
    borderFocus: '#6366F1',
    primary: '#6366F1',
    primaryHover: '#4F46E5',
    primaryFocus: '#6366F1',
    primaryActive: '#4338CA',
    success: '#16A34A',
    successHover: '#15803D',
    error: '#DC2626',
    errorHover: '#B91C1C',
    warning: '#D97706',
    warningHover: '#B45309',
    info: '#0891B2',
    infoHover: '#0E7490',
    hover: '#EDEDF5',
    active: '#E0E0ED',
    selected: '#E8E8F8',
    disabled: '#F0F0F5',
    disabledText: '#AAAAB8',
    shadow: '#C0C0D0',
    shadowHover: '#B0B0C0',
    glow: '#6366F1',
    glowSecondary: '#06B6D4',
    gradient: 'linear-gradient(90deg, #6366F1, #06B6D4, #8B5CF6)',
  },
  typography: { ...lightDefaults.typography, letterSpacing: '0.04em', textTransform: 'uppercase' },
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #C0C0D0', boxShadowHover: '6px 6px 0 #B0B0C0', glowIntensity: 0.2 },
  components: lightDefaults.components,
}

// ─── VS CODE LIGHT ──────────────────────────────────
export const vscodeLightTheme: GlobalTheme = {
  name: "VS CODE LIGHT",
  description: "The editor you live in — Light mode",
  colors: {
    background: '#FFFFFF',
    backgroundSecondary: '#F3F3F3',
    backgroundTertiary: '#ECECEC',
    foreground: '#1E1E1E',
    foregroundSecondary: '#616161',
    foregroundTertiary: '#999999',
    border: '#CECECE',
    borderHover: '#B0B0B0',
    borderFocus: '#007ACC',
    primary: '#007ACC',
    primaryHover: '#005F9E',
    primaryFocus: '#007ACC',
    primaryActive: '#004578',
    success: '#388A34',
    successHover: '#2E7D2E',
    error: '#D02020',
    errorHover: '#B01818',
    warning: '#BF8803',
    warningHover: '#A07000',
    info: '#1A85FF',
    infoHover: '#0070E0',
    hover: '#F0F0F0',
    active: '#E5E5E5',
    selected: '#ADD6FF',
    disabled: '#F0F0F0',
    disabledText: '#A0A0A0',
    shadow: '#C8C8C8',
    shadowHover: '#B8B8B8',
    glow: '#007ACC',
    glowSecondary: '#388A34',
    gradient: 'linear-gradient(90deg, #007ACC, #388A34, #BF8803)',
  },
  typography: { ...lightDefaults.typography, letterSpacing: '0.02em' },
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #C8C8C8', boxShadowHover: '6px 6px 0 #B8B8B8', glowIntensity: 0.15 },
  components: { ...lightDefaults.components, button: { borderWidth: '1px', shadowOffset: '4px' }, input: { borderWidth: '1px', focusRingWidth: '2px' }, card: { borderWidth: '1px', shadowIntensity: 0.3 }, modal: { backdropOpacity: 0.4, borderWidth: '1px' } },
}

// ─── MONOKAI LIGHT ──────────────────────────────────
export const monokaiLightTheme: GlobalTheme = {
  name: "MONOKAI LIGHT",
  description: "The Sublime legend — Pink and green on warm cream",
  colors: {
    background: '#FAF8F2',
    backgroundSecondary: '#F0EDE5',
    backgroundTertiary: '#E6E3D8',
    foreground: '#272822',
    foregroundSecondary: '#5C5C50',
    foregroundTertiary: '#908E82',
    border: '#D0CEC2',
    borderHover: '#B8B6AA',
    borderFocus: '#F92672',
    primary: '#F92672',
    primaryHover: '#D41D60',
    primaryFocus: '#F92672',
    primaryActive: '#B8164C',
    success: '#6B8E23',
    successHover: '#5A7A1C',
    error: '#F92672',
    errorHover: '#D41D60',
    warning: '#C4A800',
    warningHover: '#A89000',
    info: '#3D9FCC',
    infoHover: '#2F8AB8',
    hover: '#F0EDE5',
    active: '#E4E1D5',
    selected: '#F0E8D8',
    disabled: '#F0EDE5',
    disabledText: '#A8A69A',
    shadow: '#C8C5B8',
    shadowHover: '#B8B5A8',
    glow: '#F92672',
    glowSecondary: '#6B8E23',
    gradient: 'linear-gradient(90deg, #F92672, #6B8E23, #3D9FCC)',
  },
  typography: lightDefaults.typography,
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #C8C5B8', boxShadowHover: '6px 6px 0 #B8B5A8', glowIntensity: 0.2 },
  components: lightDefaults.components,
}

// ─── SOLARIZED LIGHT ────────────────────────────────
export const solarizedLightTheme: GlobalTheme = {
  name: "SOLARIZED LIGHT",
  description: "Color science perfected — Canonical light palette",
  colors: {
    background: '#FDF6E3',
    backgroundSecondary: '#EEE8D5',
    backgroundTertiary: '#E6DFC8',
    foreground: '#657B83',
    foregroundSecondary: '#586E75',
    foregroundTertiary: '#93A1A1',
    border: '#D6CDB4',
    borderHover: '#C0B8A0',
    borderFocus: '#268BD2',
    primary: '#268BD2',
    primaryHover: '#1A6FAA',
    primaryFocus: '#268BD2',
    primaryActive: '#155A8C',
    success: '#859900',
    successHover: '#6E8000',
    error: '#DC322F',
    errorHover: '#B82725',
    warning: '#B58900',
    warningHover: '#967000',
    info: '#2AA198',
    infoHover: '#228880',
    hover: '#EEE8D5',
    active: '#E0D8C0',
    selected: '#E8E0CC',
    disabled: '#EEE8D5',
    disabledText: '#B0A890',
    shadow: '#C8C0A8',
    shadowHover: '#B8B098',
    glow: '#268BD2',
    glowSecondary: '#2AA198',
    gradient: 'linear-gradient(90deg, #268BD2, #2AA198, #B58900)',
  },
  typography: lightDefaults.typography,
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #C8C0A8', boxShadowHover: '6px 6px 0 #B8B098', glowIntensity: 0.15 },
  components: lightDefaults.components,
}

// ─── NORD LIGHT ─────────────────────────────────────
export const nordLightTheme: GlobalTheme = {
  name: "NORD LIGHT",
  description: "Arctic frost — Cool blues on snow white",
  colors: {
    background: '#ECEFF4',
    backgroundSecondary: '#E5E9F0',
    backgroundTertiary: '#D8DEE9',
    foreground: '#2E3440',
    foregroundSecondary: '#3B4252',
    foregroundTertiary: '#7B88A1',
    border: '#C8D0E0',
    borderHover: '#B0B8C8',
    borderFocus: '#5E81AC',
    primary: '#5E81AC',
    primaryHover: '#4C6E96',
    primaryFocus: '#5E81AC',
    primaryActive: '#3E5E82',
    success: '#8FAF70',
    successHover: '#7A9A5C',
    error: '#BF616A',
    errorHover: '#A84E56',
    warning: '#D08770',
    warningHover: '#B8705A',
    info: '#88C0D0',
    infoHover: '#6AAAB8',
    hover: '#E5E9F0',
    active: '#D8DEE9',
    selected: '#D0D8E8',
    disabled: '#E5E9F0',
    disabledText: '#A0A8B8',
    shadow: '#B8C0D0',
    shadowHover: '#A8B0C0',
    glow: '#5E81AC',
    glowSecondary: '#88C0D0',
    gradient: 'linear-gradient(90deg, #5E81AC, #88C0D0, #81A1C1)',
  },
  typography: { ...lightDefaults.typography, textTransform: 'uppercase' },
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #B8C0D0', boxShadowHover: '6px 6px 0 #A8B0C0', glowIntensity: 0.15 },
  components: lightDefaults.components,
}

// ─── ONE DARK LIGHT ─────────────────────────────────
export const onedarkLightTheme: GlobalTheme = {
  name: "ONE LIGHT",
  description: "Atom's classic — Soft blue on warm white",
  colors: {
    background: '#FAFAFA',
    backgroundSecondary: '#F0F0F0',
    backgroundTertiary: '#E5E5E5',
    foreground: '#383A42',
    foregroundSecondary: '#696C77',
    foregroundTertiary: '#A0A1A7',
    border: '#D0D0D0',
    borderHover: '#B8B8B8',
    borderFocus: '#4078F2',
    primary: '#4078F2',
    primaryHover: '#3068D8',
    primaryFocus: '#4078F2',
    primaryActive: '#2858B8',
    success: '#50A14F',
    successHover: '#408A3F',
    error: '#E45649',
    errorHover: '#CA3C30',
    warning: '#C18401',
    warningHover: '#A06E00',
    info: '#0184BC',
    infoHover: '#006E9C',
    hover: '#F0F0F0',
    active: '#E5E5E5',
    selected: '#E0E8F8',
    disabled: '#F0F0F0',
    disabledText: '#B0B0B0',
    shadow: '#C0C0C0',
    shadowHover: '#B0B0B0',
    glow: '#4078F2',
    glowSecondary: '#A626A4',
    gradient: 'linear-gradient(90deg, #4078F2, #A626A4, #50A14F)',
  },
  typography: lightDefaults.typography,
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #C0C0C0', boxShadowHover: '6px 6px 0 #B0B0B0', glowIntensity: 0.15 },
  components: lightDefaults.components,
}

// ─── TOKYO NIGHT LIGHT ──────────────────────────────
export const tokyonightLightTheme: GlobalTheme = {
  name: "TOKYO DAY",
  description: "Daylight city — Soft blue on paper white",
  colors: {
    background: '#F5F5FA',
    backgroundSecondary: '#EAEAF0',
    backgroundTertiary: '#DEDEE8',
    foreground: '#343B58',
    foregroundSecondary: '#565C78',
    foregroundTertiary: '#9098B8',
    border: '#C8C8E0',
    borderHover: '#B0B0C8',
    borderFocus: '#3D59A1',
    primary: '#3D59A1',
    primaryHover: '#2E4A88',
    primaryFocus: '#3D59A1',
    primaryActive: '#254080',
    success: '#587539',
    successHover: '#486230',
    error: '#8C4351',
    errorHover: '#733640',
    warning: '#8F5E15',
    warningHover: '#784E10',
    info: '#166775',
    infoHover: '#105560',
    hover: '#EAEAF0',
    active: '#DEDEE8',
    selected: '#D8D8F0',
    disabled: '#EAEAF0',
    disabledText: '#A0A0B8',
    shadow: '#B8B8D0',
    shadowHover: '#A8A8C0',
    glow: '#3D59A1',
    glowSecondary: '#7847BD',
    gradient: 'linear-gradient(90deg, #3D59A1, #7847BD, #166775)',
  },
  typography: { ...lightDefaults.typography, letterSpacing: '0.04em', textTransform: 'uppercase' },
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #B8B8D0', boxShadowHover: '6px 6px 0 #A8A8C0', glowIntensity: 0.15 },
  components: lightDefaults.components,
}

// ─── CATPPUCCIN LIGHT (Latte) ───────────────────────
export const catppuccinLightTheme: GlobalTheme = {
  name: "CATPPUCCIN LATTE",
  description: "Pastel perfection — Mauve on warm latte",
  colors: {
    background: '#EFF1F5',
    backgroundSecondary: '#E6E9EF',
    backgroundTertiary: '#DCE0E8',
    foreground: '#4C4F69',
    foregroundSecondary: '#5C5F77',
    foregroundTertiary: '#8C8FA1',
    border: '#CCD0DA',
    borderHover: '#B8BCC8',
    borderFocus: '#8839EF',
    primary: '#8839EF',
    primaryHover: '#7028D6',
    primaryFocus: '#8839EF',
    primaryActive: '#6020BC',
    success: '#40A02B',
    successHover: '#338822',
    error: '#D20F39',
    errorHover: '#B00C30',
    warning: '#DF8E1D',
    warningHover: '#C07815',
    info: '#04A5E5',
    infoHover: '#0388C0',
    hover: '#E6E9EF',
    active: '#DCE0E8',
    selected: '#E0D8F0',
    disabled: '#E6E9EF',
    disabledText: '#A0A4B0',
    shadow: '#BCC0CC',
    shadowHover: '#ACB0BC',
    glow: '#8839EF',
    glowSecondary: '#EA76CB',
    gradient: 'linear-gradient(90deg, #8839EF, #EA76CB, #04A5E5)',
  },
  typography: lightDefaults.typography,
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #BCC0CC', boxShadowHover: '6px 6px 0 #ACB0BC', glowIntensity: 0.15 },
  components: lightDefaults.components,
}

// ─── GRUVBOX LIGHT ──────────────────────────────────
export const gruvboxLightTheme: GlobalTheme = {
  name: "GRUVBOX LIGHT",
  description: "Retro warmth — Orange on warm cream",
  colors: {
    background: '#FBF1C7',
    backgroundSecondary: '#F2E5BC',
    backgroundTertiary: '#EBDBB2',
    foreground: '#3C3836',
    foregroundSecondary: '#504945',
    foregroundTertiary: '#928374',
    border: '#D5C4A1',
    borderHover: '#BDAE93',
    borderFocus: '#D65D0E',
    primary: '#D65D0E',
    primaryHover: '#B84D0A',
    primaryFocus: '#D65D0E',
    primaryActive: '#9D4508',
    success: '#79740E',
    successHover: '#63600B',
    error: '#CC241D',
    errorHover: '#AA1E18',
    warning: '#D79921',
    warningHover: '#B5801A',
    info: '#458588',
    infoHover: '#386E70',
    hover: '#F2E5BC',
    active: '#EBDBB2',
    selected: '#F0DCA0',
    disabled: '#F2E5BC',
    disabledText: '#A89984',
    shadow: '#C8B888',
    shadowHover: '#B8A878',
    glow: '#D65D0E',
    glowSecondary: '#D79921',
    gradient: 'linear-gradient(90deg, #D65D0E, #D79921, #79740E)',
  },
  typography: { ...lightDefaults.typography, letterSpacing: '0.04em', textTransform: 'uppercase' },
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #C8B888', boxShadowHover: '6px 6px 0 #B8A878', glowIntensity: 0.2 },
  components: lightDefaults.components,
}

// ─── VERCEL LIGHT ───────────────────────────────────
export const vercelLightTheme: GlobalTheme = {
  name: "VERCEL LIGHT",
  description: "Ship fast — Clean white with precise black",
  colors: {
    background: '#FFFFFF',
    backgroundSecondary: '#FAFAFA',
    backgroundTertiary: '#F5F5F5',
    foreground: '#171717',
    foregroundSecondary: '#525252',
    foregroundTertiary: '#A3A3A3',
    border: '#E5E5E5',
    borderHover: '#D4D4D4',
    borderFocus: '#171717',
    primary: '#171717',
    primaryHover: '#000000',
    primaryFocus: '#171717',
    primaryActive: '#000000',
    success: '#17B169',
    successHover: '#129A5A',
    error: '#E5484D',
    errorHover: '#CD3D42',
    warning: '#F5A623',
    warningHover: '#D48D1A',
    info: '#0070F3',
    infoHover: '#005CC5',
    hover: '#F5F5F5',
    active: '#EBEBEB',
    selected: '#F0F0F0',
    disabled: '#FAFAFA',
    disabledText: '#C0C0C0',
    shadow: '#D4D4D4',
    shadowHover: '#C4C4C4',
    glow: '#171717',
    glowSecondary: '#A3A3A3',
    gradient: 'linear-gradient(90deg, #171717, #A3A3A3, #171717)',
  },
  typography: { ...lightDefaults.typography, letterSpacing: '0.02em' },
  effects: { ...lightDefaults.effects, boxShadow: '4px 4px 0 #D4D4D4', boxShadowHover: '6px 6px 0 #C4C4C4', glowIntensity: 0.1 },
  components: { ...lightDefaults.components, button: { borderWidth: '1px', shadowOffset: '4px' }, input: { borderWidth: '1px', focusRingWidth: '2px' }, card: { borderWidth: '1px', shadowIntensity: 0.2 }, modal: { backdropOpacity: 0.4, borderWidth: '1px' } },
}
