/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as activities_mutations from "../activities/mutations.js";
import type * as activities_queries from "../activities/queries.js";
import type * as admin_clearOldActivities from "../admin/clearOldActivities.js";
import type * as admin_inspect_links from "../admin/inspect_links.js";
import type * as admin_inspect_workspaces from "../admin/inspect_workspaces.js";
import type * as admin_link_latest from "../admin/link_latest.js";
import type * as admin_migrationStatus from "../admin/migrationStatus.js";
import type * as admin_one_off_cleanup from "../admin/one_off_cleanup.js";
import type * as agent_actions from "../agent/actions.js";
import type * as agent_context from "../agent/context.js";
import type * as agent_mutations from "../agent/mutations.js";
import type * as agent_queries from "../agent/queries.js";
import type * as agent_triage from "../agent/triage.js";
import type * as agent_triageMutations from "../agent/triageMutations.js";
import type * as ai_actions from "../ai/actions.js";
import type * as ai_generate from "../ai/generate.js";
import type * as ai_keyManagement from "../ai/keyManagement.js";
import type * as ai_mutations from "../ai/mutations.js";
import type * as ai_projectInsights from "../ai/projectInsights.js";
import type * as ai_providers from "../ai/providers.js";
import type * as ai_queries from "../ai/queries.js";
import type * as ai_resolveConfig from "../ai/resolveConfig.js";
import type * as ai_taskAssignment from "../ai/taskAssignment.js";
import type * as ai_taskAssignmentQueries from "../ai/taskAssignmentQueries.js";
import type * as ai_usageLog from "../ai/usageLog.js";
import type * as aiCredits_actions from "../aiCredits/actions.js";
import type * as aiCredits_mutations from "../aiCredits/mutations.js";
import type * as aiCredits_queries from "../aiCredits/queries.js";
import type * as analytics_queries from "../analytics/queries.js";
import type * as audit from "../audit.js";
import type * as auth_permissions from "../auth/permissions.js";
import type * as auth_users from "../auth/users.js";
import type * as automation from "../automation.js";
import type * as billing_actions from "../billing/actions.js";
import type * as billing_featureGates from "../billing/featureGates.js";
import type * as billing_mutations from "../billing/mutations.js";
import type * as billing_queries from "../billing/queries.js";
import type * as billing_webhookVerify from "../billing/webhookVerify.js";
import type * as bugReports from "../bugReports.js";
import type * as chat from "../chat.js";
import type * as clerk from "../clerk.js";
import type * as cliRefresh from "../cliRefresh.js";
import type * as comments_mutations from "../comments/mutations.js";
import type * as communications_mutations from "../communications/mutations.js";
import type * as communications_queries from "../communications/queries.js";
import type * as community_mutations from "../community/mutations.js";
import type * as community_queries from "../community/queries.js";
import type * as crons from "../crons.js";
import type * as customFields from "../customFields.js";
import type * as dashboard_queries from "../dashboard/queries.js";
import type * as developers_mutations from "../developers/mutations.js";
import type * as developers_queries from "../developers/queries.js";
import type * as documents_aiTemplates from "../documents/aiTemplates.js";
import type * as documents from "../documents.js";
import type * as email_cronHelpers from "../email/cronHelpers.js";
import type * as email_send from "../email/send.js";
import type * as email_templates from "../email/templates.js";
import type * as feedback from "../feedback.js";
import type * as filterPresets_mutations from "../filterPresets/mutations.js";
import type * as filterPresets_queries from "../filterPresets/queries.js";
import type * as gitWorkflow_mutations from "../gitWorkflow/mutations.js";
import type * as gitWorkflow_queries from "../gitWorkflow/queries.js";
import type * as http from "../http.js";
import type * as integrations_github_actions from "../integrations/github/actions.js";
import type * as integrations_github_appSimple from "../integrations/github/appSimple.js";
import type * as integrations_github_auth from "../integrations/github/auth.js";
import type * as integrations_github_backfill from "../integrations/github/backfill.js";
import type * as integrations_github_commentSync from "../integrations/github/commentSync.js";
import type * as integrations_github_commitParsing from "../integrations/github/commitParsing.js";
import type * as integrations_github_docs from "../integrations/github/docs.js";
import type * as integrations_github_errors from "../integrations/github/errors.js";
import type * as integrations_github_installationManagement from "../integrations/github/installationManagement.js";
import type * as integrations_github_issueSync from "../integrations/github/issueSync.js";
import type * as integrations_github_issueSyncMutations from "../integrations/github/issueSyncMutations.js";
import type * as integrations_github_logging from "../integrations/github/logging.js";
import type * as integrations_github_metrics from "../integrations/github/metrics.js";
import type * as integrations_github_monitoring from "../integrations/github/monitoring.js";
import type * as integrations_github_mutations from "../integrations/github/mutations.js";
import type * as integrations_github_nodeActions from "../integrations/github/nodeActions.js";
import type * as integrations_github_oauth from "../integrations/github/oauth.js";
import type * as integrations_github_projectQueries from "../integrations/github/projectQueries.js";
import type * as integrations_github_queries from "../integrations/github/queries.js";
import type * as integrations_github_queryActions from "../integrations/github/queryActions.js";
import type * as integrations_github_rateLimiter from "../integrations/github/rateLimiter.js";
import type * as integrations_github_releaseNotes from "../integrations/github/releaseNotes.js";
import type * as integrations_github_sync from "../integrations/github/sync.js";
import type * as integrations_github_syncActions from "../integrations/github/syncActions.js";
import type * as integrations_github_teamSync from "../integrations/github/teamSync.js";
import type * as integrations_github_teamSyncMutations from "../integrations/github/teamSyncMutations.js";
import type * as integrations_github_types from "../integrations/github/types.js";
import type * as integrations_github_userMapping from "../integrations/github/userMapping.js";
import type * as integrations_github_webhooks from "../integrations/github/webhooks.js";
import type * as integrations_gitlab_mutations from "../integrations/gitlab/mutations.js";
import type * as integrations_gitlab_oauth from "../integrations/gitlab/oauth.js";
import type * as integrations_gitlab_queries from "../integrations/gitlab/queries.js";
import type * as integrations_gitlab_sync from "../integrations/gitlab/sync.js";
import type * as integrations_gitlab_types from "../integrations/gitlab/types.js";
import type * as integrations_imports from "../integrations/imports.js";
import type * as integrations_jira_import from "../integrations/jira/import.js";
import type * as integrations_jira_importWorker from "../integrations/jira/importWorker.js";
import type * as integrations_jira_mutations from "../integrations/jira/mutations.js";
import type * as integrations_jira_types from "../integrations/jira/types.js";
import type * as integrations_linear_import from "../integrations/linear/import.js";
import type * as integrations_linear_importWorker from "../integrations/linear/importWorker.js";
import type * as integrations_linear_mutations from "../integrations/linear/mutations.js";
import type * as integrations_linear_types from "../integrations/linear/types.js";
import type * as integrations_slack_commands from "../integrations/slack/commands.js";
import type * as integrations_slack_events from "../integrations/slack/events.js";
import type * as integrations_slack_mutations from "../integrations/slack/mutations.js";
import type * as integrations_slack_queries from "../integrations/slack/queries.js";
import type * as internalQueries from "../internalQueries.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_validators from "../lib/validators.js";
import type * as meetings_mutations from "../meetings/mutations.js";
import type * as meetings_queries from "../meetings/queries.js";
import type * as migrations_backfillNotifications from "../migrations/backfillNotifications.js";
import type * as migrations_clearOldActivities from "../migrations/clearOldActivities.js";
import type * as migrations_migrateToMultipleAssignees from "../migrations/migrateToMultipleAssignees.js";
import type * as migrations from "../migrations.js";
import type * as notificationQueries from "../notificationQueries.js";
import type * as notifications_config from "../notifications/config.js";
import type * as notifications_dispatch from "../notifications/dispatch.js";
import type * as notifications_dispatch_helpers from "../notifications/dispatch_helpers.js";
import type * as notifications_push from "../notifications/push.js";
import type * as notifications_push_helpers from "../notifications/push_helpers.js";
import type * as nps from "../nps.js";
import type * as projects_members from "../projects/members.js";
import type * as projects_mutations from "../projects/mutations.js";
import type * as projects_queries from "../projects/queries.js";
import type * as resources from "../resources.js";
import type * as search from "../search.js";
import type * as skills_builtInSkills from "../skills/builtInSkills.js";
import type * as skills_execution from "../skills/execution.js";
import type * as skills_internalQueries from "../skills/internalQueries.js";
import type * as skills_mutations from "../skills/mutations.js";
import type * as skills_queries from "../skills/queries.js";
import type * as sprints_mutations from "../sprints/mutations.js";
import type * as sprints_queries from "../sprints/queries.js";
import type * as sprints_snapshots from "../sprints/snapshots.js";
import type * as tasks_mutations from "../tasks/mutations.js";
import type * as tasks_queries from "../tasks/queries.js";
import type * as teams from "../teams.js";
import type * as timeEntries from "../timeEntries.js";
import type * as video from "../video.js";
import type * as waitlist from "../waitlist.js";
import type * as whiteboard from "../whiteboard.js";
import type * as workspaces_mutations from "../workspaces/mutations.js";
import type * as workspaces_queries from "../workspaces/queries.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "activities/mutations": typeof activities_mutations;
  "activities/queries": typeof activities_queries;
  "admin/clearOldActivities": typeof admin_clearOldActivities;
  "admin/inspect_links": typeof admin_inspect_links;
  "admin/inspect_workspaces": typeof admin_inspect_workspaces;
  "admin/link_latest": typeof admin_link_latest;
  "admin/migrationStatus": typeof admin_migrationStatus;
  "admin/one_off_cleanup": typeof admin_one_off_cleanup;
  "agent/actions": typeof agent_actions;
  "agent/context": typeof agent_context;
  "agent/mutations": typeof agent_mutations;
  "agent/queries": typeof agent_queries;
  "agent/triage": typeof agent_triage;
  "agent/triageMutations": typeof agent_triageMutations;
  "ai/actions": typeof ai_actions;
  "ai/generate": typeof ai_generate;
  "ai/keyManagement": typeof ai_keyManagement;
  "ai/mutations": typeof ai_mutations;
  "ai/projectInsights": typeof ai_projectInsights;
  "ai/providers": typeof ai_providers;
  "ai/queries": typeof ai_queries;
  "ai/resolveConfig": typeof ai_resolveConfig;
  "ai/taskAssignment": typeof ai_taskAssignment;
  "ai/taskAssignmentQueries": typeof ai_taskAssignmentQueries;
  "ai/usageLog": typeof ai_usageLog;
  "aiCredits/actions": typeof aiCredits_actions;
  "aiCredits/mutations": typeof aiCredits_mutations;
  "aiCredits/queries": typeof aiCredits_queries;
  "analytics/queries": typeof analytics_queries;
  audit: typeof audit;
  "auth/permissions": typeof auth_permissions;
  "auth/users": typeof auth_users;
  automation: typeof automation;
  "billing/actions": typeof billing_actions;
  "billing/featureGates": typeof billing_featureGates;
  "billing/mutations": typeof billing_mutations;
  "billing/queries": typeof billing_queries;
  "billing/webhookVerify": typeof billing_webhookVerify;
  bugReports: typeof bugReports;
  chat: typeof chat;
  clerk: typeof clerk;
  cliRefresh: typeof cliRefresh;
  "comments/mutations": typeof comments_mutations;
  "communications/mutations": typeof communications_mutations;
  "communications/queries": typeof communications_queries;
  "community/mutations": typeof community_mutations;
  "community/queries": typeof community_queries;
  crons: typeof crons;
  customFields: typeof customFields;
  "dashboard/queries": typeof dashboard_queries;
  "developers/mutations": typeof developers_mutations;
  "developers/queries": typeof developers_queries;
  "documents/aiTemplates": typeof documents_aiTemplates;
  documents: typeof documents;
  "email/cronHelpers": typeof email_cronHelpers;
  "email/send": typeof email_send;
  "email/templates": typeof email_templates;
  feedback: typeof feedback;
  "filterPresets/mutations": typeof filterPresets_mutations;
  "filterPresets/queries": typeof filterPresets_queries;
  "gitWorkflow/mutations": typeof gitWorkflow_mutations;
  "gitWorkflow/queries": typeof gitWorkflow_queries;
  http: typeof http;
  "integrations/github/actions": typeof integrations_github_actions;
  "integrations/github/appSimple": typeof integrations_github_appSimple;
  "integrations/github/auth": typeof integrations_github_auth;
  "integrations/github/backfill": typeof integrations_github_backfill;
  "integrations/github/commentSync": typeof integrations_github_commentSync;
  "integrations/github/commitParsing": typeof integrations_github_commitParsing;
  "integrations/github/docs": typeof integrations_github_docs;
  "integrations/github/errors": typeof integrations_github_errors;
  "integrations/github/installationManagement": typeof integrations_github_installationManagement;
  "integrations/github/issueSync": typeof integrations_github_issueSync;
  "integrations/github/issueSyncMutations": typeof integrations_github_issueSyncMutations;
  "integrations/github/logging": typeof integrations_github_logging;
  "integrations/github/metrics": typeof integrations_github_metrics;
  "integrations/github/monitoring": typeof integrations_github_monitoring;
  "integrations/github/mutations": typeof integrations_github_mutations;
  "integrations/github/nodeActions": typeof integrations_github_nodeActions;
  "integrations/github/oauth": typeof integrations_github_oauth;
  "integrations/github/projectQueries": typeof integrations_github_projectQueries;
  "integrations/github/queries": typeof integrations_github_queries;
  "integrations/github/queryActions": typeof integrations_github_queryActions;
  "integrations/github/rateLimiter": typeof integrations_github_rateLimiter;
  "integrations/github/releaseNotes": typeof integrations_github_releaseNotes;
  "integrations/github/sync": typeof integrations_github_sync;
  "integrations/github/syncActions": typeof integrations_github_syncActions;
  "integrations/github/teamSync": typeof integrations_github_teamSync;
  "integrations/github/teamSyncMutations": typeof integrations_github_teamSyncMutations;
  "integrations/github/types": typeof integrations_github_types;
  "integrations/github/userMapping": typeof integrations_github_userMapping;
  "integrations/github/webhooks": typeof integrations_github_webhooks;
  "integrations/gitlab/mutations": typeof integrations_gitlab_mutations;
  "integrations/gitlab/oauth": typeof integrations_gitlab_oauth;
  "integrations/gitlab/queries": typeof integrations_gitlab_queries;
  "integrations/gitlab/sync": typeof integrations_gitlab_sync;
  "integrations/gitlab/types": typeof integrations_gitlab_types;
  "integrations/imports": typeof integrations_imports;
  "integrations/jira/import": typeof integrations_jira_import;
  "integrations/jira/importWorker": typeof integrations_jira_importWorker;
  "integrations/jira/mutations": typeof integrations_jira_mutations;
  "integrations/jira/types": typeof integrations_jira_types;
  "integrations/linear/import": typeof integrations_linear_import;
  "integrations/linear/importWorker": typeof integrations_linear_importWorker;
  "integrations/linear/mutations": typeof integrations_linear_mutations;
  "integrations/linear/types": typeof integrations_linear_types;
  "integrations/slack/commands": typeof integrations_slack_commands;
  "integrations/slack/events": typeof integrations_slack_events;
  "integrations/slack/mutations": typeof integrations_slack_mutations;
  "integrations/slack/queries": typeof integrations_slack_queries;
  internalQueries: typeof internalQueries;
  "lib/auth": typeof lib_auth;
  "lib/validators": typeof lib_validators;
  "meetings/mutations": typeof meetings_mutations;
  "meetings/queries": typeof meetings_queries;
  "migrations/backfillNotifications": typeof migrations_backfillNotifications;
  "migrations/clearOldActivities": typeof migrations_clearOldActivities;
  "migrations/migrateToMultipleAssignees": typeof migrations_migrateToMultipleAssignees;
  migrations: typeof migrations;
  notificationQueries: typeof notificationQueries;
  "notifications/config": typeof notifications_config;
  "notifications/dispatch": typeof notifications_dispatch;
  "notifications/dispatch_helpers": typeof notifications_dispatch_helpers;
  "notifications/push": typeof notifications_push;
  "notifications/push_helpers": typeof notifications_push_helpers;
  nps: typeof nps;
  "projects/members": typeof projects_members;
  "projects/mutations": typeof projects_mutations;
  "projects/queries": typeof projects_queries;
  resources: typeof resources;
  search: typeof search;
  "skills/builtInSkills": typeof skills_builtInSkills;
  "skills/execution": typeof skills_execution;
  "skills/internalQueries": typeof skills_internalQueries;
  "skills/mutations": typeof skills_mutations;
  "skills/queries": typeof skills_queries;
  "sprints/mutations": typeof sprints_mutations;
  "sprints/queries": typeof sprints_queries;
  "sprints/snapshots": typeof sprints_snapshots;
  "tasks/mutations": typeof tasks_mutations;
  "tasks/queries": typeof tasks_queries;
  teams: typeof teams;
  timeEntries: typeof timeEntries;
  video: typeof video;
  waitlist: typeof waitlist;
  whiteboard: typeof whiteboard;
  "workspaces/mutations": typeof workspaces_mutations;
  "workspaces/queries": typeof workspaces_queries;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
